version: "3.8"

services:
  root-nameserver:
    container_name: root
    image: bind9/bind9:v${BIND9_VERSION}
    command: bash -c "sh entrypoint.sh  &&  named -g -c /etc/bind/named.conf"
    volumes:
      - ./config/root/:/etc/bind/bindtmps/
    environment:
      - HOST_IP=${ROOT_SERVER_IP}
      - TOP_LEVEL_SERVER_IP=${TOP_LEVEL_SERVER_IP}
    networks:
      nameserver_bridge:
        ipv4_address: ${ROOT_SERVER_IP}
    deploy:
      resources:
        limits:
          cpus: "1"
  toplevel-nameserver:
    container_name: toplevel
    image: bind9/bind9:v${BIND9_VERSION}
    command: bash -c "sh entrypoint.sh && named -g -c /etc/bind/named.conf"
    volumes:
      - ./config/toplevel/:/etc/bind/bindtmps
    environment:
      - HOST_IP=${TOP_LEVEL_SERVER_IP}
      - AUTHORITATIVE_SERVER1a_IP=${AUTHORITATIVE_SERVER1a_IP}
      - AUTHORITATIVE_SERVER2a_IP=${AUTHORITATIVE_SERVER2a_IP}
    networks:
      nameserver_bridge:
        ipv4_address: ${TOP_LEVEL_SERVER_IP}
  authoritative-nameserver1a:
    container_name: authoritative1a
    image: bind9/bind9:v${BIND9_VERSION}
    command: bash -c "sh entrypoint.sh  && named -g -c /etc/bind/named.conf "
    volumes:
      - ./config/authoritative1a/:/etc/bind/bindtmps
    environment:
      - HOST_IP=${AUTHORITATIVE_SERVER1a_IP}
      - AUTHORITATIVE_SERVER2a_IP=${AUTHORITATIVE_SERVER2a_IP}
    networks:
      nameserver_bridge:
        ipv4_address: ${AUTHORITATIVE_SERVER1a_IP}
  authoritative-nameserver2a:
    container_name: authoritative2a
    image: bind9/bind9:v${BIND9_VERSION}
    command: bash -c "sh entrypoint.sh  && named -g -c /etc/bind/named.conf "
    volumes:
      - ./config/authoritative2a/:/etc/bind/bindtmps
    environment:
      - HOST_IP=${AUTHORITATIVE_SERVER2a_IP}
      - AUTHORITATIVE_SERVER1a_IP=${AUTHORITATIVE_SERVER1a_IP}
    networks:
      nameserver_bridge:
        ipv4_address: ${AUTHORITATIVE_SERVER2a_IP}
  resolver1:
    container_name: resolver1
    image: bind9/bind9:v${BIND9_VERSION}
    command: bash -c "sh entrypoint.sh  && named -g -c /etc/bind/named.conf"
    volumes:
      - ./config/resolver/:/etc/bind/bindtmps
    environment:
      - ROOT_SERVER_IP=${ROOT_SERVER_IP}
    networks:
      nameserver_bridge:
        ipv4_address: ${RESOLVER_SERVER1_IP}

networks:
  nameserver_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  prom_data:
