{
 "title": "DNS Monitoring",
 "time": { "from": "2024-10-10T15:08:56.710Z", "to": "2024-10-10T15:12:14.388Z" },
 "panels": [
  {
   "title": "Root Nameserver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"root\"}[1m])) * 100\r\n",
     "legendFormat": "Root"
    }
   ]
  },
  {
   "title": "Root Nameserver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"root\"} / 1024 /1024 ",
     "legendFormat": "Root"
    }
   ]
  },
  {
   "title": "Root Nameserver Received/Transmitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"root\"}[1m]) / 1024",
     "legendFormat": "Received Rate"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"root\"}[1m]) / 1024",
     "legendFormat": "Transmitted Rate"
    }
   ]
  },
  {
   "title": "Top Level Nameserver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"toplevel\"}[1m])) * 100",
     "legendFormat": "toplevel"
    }
   ]
  },
  {
   "title": "TopLevel Nameserver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"toplevel\"} / 1024 /1024 ",
     "legendFormat": "toplevel"
    }
   ]
  },
  {
   "title": "TopLevel Nameserver Received/Transmitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"toplevel\"}[1m]) / 1024",
     "legendFormat": "Received Rate"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"toplevel\"}[1m]) / 1024",
     "legendFormat": "Transmitted Rate"
    }
   ]
  },
  {
   "title": "Authoritative Nameserver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"authoritative1a\"}[1m])) * 100",
     "legendFormat": "authoritative1a"
    }
   ]
  },
  {
   "title": "Authoritative Nameserver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"authoritative1a\"} / 1024 /1024 ",
     "legendFormat": "authoritative"
    }
   ]
  },
  {
   "title": "Authoritative Nameserver Received/Transmitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"authoritative1a\"}[1m]) / 1024",
     "legendFormat": "Received Rate"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"authoritative1a\"}[1m]) / 1024",
     "legendFormat": "Transmitted Rate"
    }
   ]
  },
  {
   "title": "Resolver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"resolver1\"}[1m])) * 100",
     "legendFormat": "Resolver "
    }
   ]
  },
  {
   "title": "Resolver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"resolver1\"} / 1024 /1024 ",
     "legendFormat": "Resolver "
    }
   ]
  },
  {
   "title": "Resolver Received/Transmitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"resolver1\"}[1m]) / 1024",
     "legendFormat": "Received Rate"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"resolver1\"}[1m]) / 1024",
     "legendFormat": "Transmitted Rate"
    }
   ]
  }
 ]
}